# Generated by Django 5.0 on 2023-12-15 23:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0002_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
